print('...')
print('...')
print('...')
print('...')
print('...')
print('...')
print('Backend line coverage check completed.')
print('Backend line coverage is 100%.')
print('')
print('Running Backend branch coverage check...')
print('...')
print('...')
print('...')
print('...')
print('...')
print('...')
print('...')
print('Backend branch coverage check completed.')
print('\033[1m' + 'core.storage.feedback.gae_models.py' + '\033[0m' + ' is not fully tested. Make sure it is fully covered before pushing the code.')
print('Push aborted due to incomplete backend coverage.')
print('Already on \'testing-coverage\'')